# Generated by Django 4.2.9 on 2024-01-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
