# Generated by Django 4.2.9 on 2024-01-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=714),
            preserve_default=False,
        ),
    ]
