# Generated by Django 4.2.9 on 2024-01-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.IntegerField(default=1106),
            preserve_default=False,
        ),
    ]
