# Generated by Django 4.2.9 on 2024-01-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_products_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=86, max_digits=10),
            preserve_default=False,
        ),
    ]
